name: Lint

on:
    pull_request:
    push:

jobs:
    lint:
        if: contains(github.event.commits[0].message, '[ci]') == false
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Install NPM dependencies and compile
              uses: bahmutov/npm-install@v1.7.4

            - name: Run ESLint
              run: npm run eslint